name: Build tool

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Install GCC (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        choco install mingw -y
        echo "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin" >> $env:GITHUB_PATH

    - name: Compile
      run: |
        gcc -Wall -o tl-ips-tool src/*.c

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: tl-ips-tool-${{ matrix.os }}
        path: |
          name: Build C program

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Install GCC (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        choco install mingw -y
        echo "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin" >> $env:GITHUB_PATH

    - name: Compile
      run: |
        gcc -Wall -o tl-attr-tool src/*.c

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: tl-attr-tool-${{ matrix.os }}
        path: |
          tl-attr-tool*tl-ips-tool*
